### ISSUE TITLE
Добавить конфиги к ботам

### ISSUE THREAD

**Issue by selevit** [umputun/rt-bot#93]
Для ботов поддерживаются конфиги, которые описывают базовую информацию о боте и его тесткейсы.
На основе этих конфигов происходит функциональное тестирование бота в travis.
В будущем, по нему же, возможно, будет происходить автоматическая регистрация бота.

Нужно запилить конфигурационные файлы для всех ботов.

Пример конфига для карма-бота:

```yaml
bot_name: "karma-bot"

defaults:
  username: "test-user"
  display_name: "Test User"

ignored_commands:
  - "Ignored message 1"
  - "Ignored message 2"
  - "Ignored message 3"

test_cases:
  - command: "/karma selevit"
    result: "^Карма пользователя @selevit: \\d+.$"

  - command:
      username: "selevit"
      text: "selevit +1"
    result: "^Вы не можете изменять свою карму!$"

  - command: "selevit++"
    result: "^Карма пользователя @selevit увеличена \\(текущее значение: \\d+\\).$"
```

**Comment by terbooter** [comment]
Позвольте высказать свои соображения.
Функциональное тестирование и конфиг с описанием бота, конечно, нужны и важны.
@selevit, cпасибо!

Но есть нюансы:
 - Два конфига слиплись вместе. Предлагаю конфиг с описанием бота сделать отдельно (может пока он и не нужен). И конфиг с функциональными тестами отдельно.

 - Конфиг получился не интуитивный, за кадром остались неявные утверждения. Например, http коды ответов. Конфиг функционального теста переусложнен, не подчеркивает простую природу REST сервиса. Предлагаю понизить знание тестов о внутренней природе сервисов до уровня http запрос-ответ.
Пример конфига для тестов
```yaml
 test:
  request:
    url: /info 
  response:
    code: 200
    json:
     info: ...
     author: ...

 test:
  request:
    url: /event
    json:
      text: ...
      username: ...
      display_name: ... 
  response:
    code: 201
    json:
     text: ...
     bot: ...
```
